FROM node:21-alpine
WORKDIR /usr/src/app
RUN npm install react-webcam --save
RUN npm install axios --save
RUN npm install js-cookie --save
RUN npm install recoil --save
RUN npm install websocket --save